export const products = [
  {
    id: 'core-midnight-thread',
    slug: 'midnight-thread',
    name: 'Midnight Thread',
    collection: 'Core',
    price: 128,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#10131b', '#f5efe4'],
    description: 'Silky premium cotton tee with a quiet, gallery-led silhouette.',
    modelPath: '/models/tshirts/midnight-thread.glb',
    texturePath: '/textures/prints/midnight-thread.webp',
    normalMapPath: '/textures/fabrics/premium-cotton-normal.webp',
    printDesignPath: '/textures/prints/midnight-thread-print.webp',
    fabricWeight: '210g/m²',
    threadCount: 180,
    accentColor: '#d4af7a',
    theme: 'quiet-luxury',
    vaultLocked: false,
    arPalette: ['charcoal', 'cream', 'gold'],
  },
  {
    id: 'core-atelier-stone',
    slug: 'atelier-stone',
    name: 'Atelier Stone',
    collection: 'Core',
    price: 122,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#d8ccbf', '#35373f'],
    description: 'Minimal drape with subtle weight and a softened hand-feel.',
    modelPath: '/models/tshirts/atelier-stone.glb',
    texturePath: '/textures/prints/atelier-stone.webp',
    normalMapPath: '/textures/fabrics/premium-cotton-normal.webp',
    printDesignPath: '/textures/prints/atelier-stone-print.webp',
    fabricWeight: '205g/m²',
    threadCount: 176,
    accentColor: '#c6b5a1',
    theme: 'stone-gallery',
    vaultLocked: false,
    arPalette: ['stone', 'graphite', 'linen'],
  },
  {
    id: 'esclusivo-verdant-code',
    slug: 'verdant-code',
    name: 'Verdant Code',
    collection: 'Esclusivo',
    price: 168,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#6a8f4e', '#0d1510'],
    description: 'Exclusive pigment wash with crisp structure and clean luxury finish.',
    modelPath: '/models/tshirts/verdant-code.glb',
    texturePath: '/textures/prints/verdant-code.webp',
    normalMapPath: '/textures/fabrics/premium-cotton-normal.webp',
    printDesignPath: '/textures/prints/verdant-code-print.webp',
    fabricWeight: '220g/m²',
    threadCount: 182,
    accentColor: '#8ab36e',
    theme: 'organic-luxe',
    vaultLocked: true,
    arPalette: ['moss', 'forest', 'sage'],
  },
  {
    id: 'rare-neon-afterglow',
    slug: 'neon-afterglow',
    name: 'Neon Afterglow',
    collection: 'Rare',
    price: 188,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#2d163f', '#ef5cff'],
    description: 'Limited-edition graphic treatment built for bold visual storytelling.',
    modelPath: '/models/tshirts/neon-afterglow.glb',
    texturePath: '/textures/prints/neon-afterglow.webp',
    normalMapPath: '/textures/fabrics/premium-cotton-normal.webp',
    printDesignPath: '/textures/prints/neon-afterglow-print.webp',
    fabricWeight: '215g/m²',
    threadCount: 184,
    accentColor: '#ff5ad8',
    theme: 'urban-electric',
    vaultLocked: true,
    arPalette: ['magenta', 'violet', 'cyan'],
  },
  {
    id: 'esclusivo-ivory-script',
    slug: 'ivory-script',
    name: 'Ivory Script',
    collection: 'Esclusivo',
    price: 172,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#efe7da', '#7f6f61'],
    description: 'Soft ivory body with editorial linework and museum-grade restraint.',
    modelPath: '/models/tshirts/ivory-script.glb',
    texturePath: '/textures/prints/ivory-script.webp',
    normalMapPath: '/textures/fabrics/premium-cotton-normal.webp',
    printDesignPath: '/textures/prints/ivory-script-print.webp',
    fabricWeight: '208g/m²',
    threadCount: 178,
    accentColor: '#b8a58d',
    theme: 'editorial-quiet',
    vaultLocked: true,
    arPalette: ['ivory', 'sand', 'taupe'],
  },
  {
    id: 'rare-aurora-grid',
    slug: 'aurora-grid',
    name: 'Aurora Grid',
    collection: 'Rare',
    price: 194,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#141d34', '#71ddff'],
    description: 'Sharp geometric print with a cool-spectrum glow built for the urban gallery.',
    modelPath: '/models/tshirts/aurora-grid.glb',
    texturePath: '/textures/prints/aurora-grid.webp',
    normalMapPath: '/textures/fabrics/premium-cotton-normal.webp',
    printDesignPath: '/textures/prints/aurora-grid-print.webp',
    fabricWeight: '218g/m²',
    threadCount: 186,
    accentColor: '#71ddff',
    theme: 'electric-grid',
    vaultLocked: true,
    arPalette: ['cyan', 'navy', 'ice'],
  },
];

export const getProductById = (id) => products.find((product) => product.id === id);
export const getVaultProducts = () => products.filter((product) => product.collection !== 'Core');
