const productBase = '/models/tshirts';
const printBase = '/textures/prints';
const fabricBase = '/textures/fabrics';

export const products = [
  {
    id: 'core-midnight-thread',
    slug: 'midnight-thread',
    name: 'Midnight Thread',
    collection: 'Core',
    price: 128,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#10131b', '#f5efe4'],
    description: 'Quiet-luxury cotton jersey with a clean fall and soft hand-feel.',
    modelPath: `${productBase}/midnight-thread.glb`,
    texturePath: `${printBase}/midnight-thread.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/midnight-thread-print.webp`,
    fabricWeight: 210,
    threadCount: 180,
    accentColor: '#d4af7a',
    vaultLocked: false,
  },
  {
    id: 'core-atelier-stone',
    slug: 'atelier-stone',
    name: 'Atelier Stone',
    collection: 'Core',
    price: 122,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#d8ccbf', '#35373f'],
    description: 'Structured premium cotton with an understated gallery palette.',
    modelPath: `${productBase}/atelier-stone.glb`,
    texturePath: `${printBase}/atelier-stone.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/atelier-stone-print.webp`,
    fabricWeight: 205,
    threadCount: 176,
    accentColor: '#c6b5a1',
    vaultLocked: false,
  },
  {
    id: 'core-noir-selvedge',
    slug: 'noir-selvedge',
    name: 'Noir Selvedge',
    collection: 'Core',
    price: 132,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#17181d', '#9197a8'],
    description: 'Dense cotton knit designed for crisp drape and dark tonal styling.',
    modelPath: `${productBase}/noir-selvedge.glb`,
    texturePath: `${printBase}/noir-selvedge.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/noir-selvedge-print.webp`,
    fabricWeight: 214,
    threadCount: 182,
    accentColor: '#8e98b4',
    vaultLocked: false,
  },
  {
    id: 'core-gallery-sand',
    slug: 'gallery-sand',
    name: 'Gallery Sand',
    collection: 'Core',
    price: 124,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['#efe4d0', '#6c645a'],
    description: 'Soft beige cotton tee with refined weight and minimal linework.',
    modelPath: `${productBase}/gallery-sand.glb`,
    texturePath: `${printBase}/gallery-sand.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/gallery-sand-print.webp`,
    fabricWeight: 208,
    threadCount: 177,
    accentColor: '#cdb28f',
    vaultLocked: false,
  },
  {
    id: 'esclusivo-verdant-code',
    slug: 'verdant-code',
    name: 'Verdant Code',
    collection: 'Esclusivo',
    price: 168,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#6a8f4e', '#0d1510'],
    description: 'Exclusive pigment-washed cotton with sharp structure and quiet rarity.',
    modelPath: `${productBase}/verdant-code.glb`,
    texturePath: `${printBase}/verdant-code.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/verdant-code-print.webp`,
    fabricWeight: 220,
    threadCount: 182,
    accentColor: '#8ab36e',
    vaultLocked: true,
  },
  {
    id: 'esclusivo-ivory-script',
    slug: 'ivory-script',
    name: 'Ivory Script',
    collection: 'Esclusivo',
    price: 172,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#efe7da', '#7f6f61'],
    description: 'A clean ivory body with editorial restraint and softer cotton loft.',
    modelPath: `${productBase}/ivory-script.glb`,
    texturePath: `${printBase}/ivory-script.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/ivory-script-print.webp`,
    fabricWeight: 208,
    threadCount: 178,
    accentColor: '#b8a58d',
    vaultLocked: true,
  },
  {
    id: 'esclusivo-marbled-ink',
    slug: 'marbled-ink',
    name: 'Marbled Ink',
    collection: 'Esclusivo',
    price: 176,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#1a2029', '#d9d2c7'],
    description: 'Rich cotton surface with an inky marbled print and elevated hand-feel.',
    modelPath: `${productBase}/marbled-ink.glb`,
    texturePath: `${printBase}/marbled-ink.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/marbled-ink-print.webp`,
    fabricWeight: 216,
    threadCount: 183,
    accentColor: '#d2c2ac',
    vaultLocked: true,
  },
  {
    id: 'rare-neon-afterglow',
    slug: 'neon-afterglow',
    name: 'Neon Afterglow',
    collection: 'Rare',
    price: 188,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#2d163f', '#ef5cff'],
    description: 'A limited graphic cotton piece designed for bold spatial storytelling.',
    modelPath: `${productBase}/neon-afterglow.glb`,
    texturePath: `${printBase}/neon-afterglow.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/neon-afterglow-print.webp`,
    fabricWeight: 215,
    threadCount: 184,
    accentColor: '#ff5ad8',
    vaultLocked: true,
  },
  {
    id: 'rare-aurora-grid',
    slug: 'aurora-grid',
    name: 'Aurora Grid',
    collection: 'Rare',
    price: 194,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#141d34', '#71ddff'],
    description: 'A geometric print energized by cool-spectrum contrast and premium cotton density.',
    modelPath: `${productBase}/aurora-grid.glb`,
    texturePath: `${printBase}/aurora-grid.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/aurora-grid-print.webp`,
    fabricWeight: 218,
    threadCount: 186,
    accentColor: '#71ddff',
    vaultLocked: true,
  },
  {
    id: 'rare-celestial-grid',
    slug: 'celestial-grid',
    name: 'Celestial Grid',
    collection: 'Rare',
    price: 198,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#090f1d', '#c0d2ff'],
    description: 'High-thread-count cotton with a luminous print made for collector energy.',
    modelPath: `${productBase}/celestial-grid.glb`,
    texturePath: `${printBase}/celestial-grid.webp`,
    normalMapPath: `${fabricBase}/premium-cotton-normal.webp`,
    printDesignPath: `${printBase}/celestial-grid-print.webp`,
    fabricWeight: 221,
    threadCount: 188,
    accentColor: '#c0d2ff',
    vaultLocked: true,
  },
];

export const getProductById = (id) => products.find((product) => product.id === id);
export const getVaultProducts = () => products.filter((product) => product.collection !== 'Core');
export const getBatchOneFeaturedProducts = () => products.slice(0, 4);
