export const SITE = {
  name: "KOLT Realty",
  brandName: "KOLT Realty",
  legal: "KOLT Realty",
  brokerage: "KOLT",
  role: "Commercial Real Estate Advisory",
  titleSuffix: "GTA Commercial Real Estate",
  tagline: "Commercial real estate guidance engineered for decisive operators.",
  description:
    "KOLT Realty presents a sharper path through GTA commercial real estate with market intelligence, practical screening frameworks, and decision support built around industrial, office, retail, and land opportunities.",
  defaultDescription:
    "KOLT Realty is a GTA commercial real estate platform built around sharper shortlists, cleaner comparisons, and more confident decisions across industrial, warehouse, office, retail, and land opportunities.",
  productionUrl: "https://kolt-realty.vercel.app",
  socialPreviewPath: "/social-preview.svg",
  primaryColor: "#B01F24",
  darkColor: "#121212",
  lightColor: "#F6F3EF",
  accentColor: "#D9C9B5",
  primaryEmail: "approval-pending@koltrealty.ca",
  primaryPhone: "+1-000-000-0000",
  officeAddress: "Address withheld pending approval",
  socialProfiles: [],
  serviceAreas: [
    "Toronto",
    "Vaughan",
    "Mississauga",
    "Brampton",
    "Markham",
    "North York",
    "Richmond Hill",
    "Etobicoke",
  ],
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Listings", href: "/listings" },
    { label: "Tools", href: "/tools" },
    { label: "Guides", href: "/guides" },
    { label: "Why KOLT", href: "/why-kolt" },
    { label: "About", href: "/about" },
  ],
  footerNav: [
    { label: "Markets", href: "/markets" },
    { label: "Asset Classes", href: "/asset-classes" },
    { label: "Checklists", href: "/checklists" },
    { label: "Warehouse Demo", href: "/warehouse" },
    { label: "Interactive Showcase", href: "/listing-type-2" },
    { label: "Contact", href: "/contact" },
  ],
  proofPoints: [
    "Industrial, office, retail, and land",
    "GTA corridor focus",
    "Decision-first client journey",
    "Interactive warehouse showcase",
  ],
};
